import java.util.Properties;

import javax.naming.InitialContext;
import javax.naming.NamingException;
import test.TestRemote;


public class test {

	public test() {
		// TODO Auto-generated constructor stub
	}

	static InitialContext ctx;
    static{
    	
    }
	
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Properties jndiProps = new Properties();
        jndiProps.put(InitialContext.INITIAL_CONTEXT_FACTORY, "org.jboss.naming.remote.client.InitialContextFactory");
        jndiProps.put(InitialContext.PROVIDER_URL,"remote://localhost:4447");// create a context passing these properties
        // username
        jndiProps.put(InitialContext.SECURITY_PRINCIPAL, "user");
        // password
        jndiProps.put(InitialContext.SECURITY_CREDENTIALS, "12345");
        try {
			ctx = new InitialContext(jndiProps);
		} catch (NamingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		try {
			TestRemote test1 = (TestRemote)ctx.lookup("EnterpriseServer/test.Test");
			String res = test1.getResult();
			System.out.println(res);
			
		} catch (NamingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
