// default package
// Generated Mar 26, 2013 11:20:30 PM by Hibernate Tools 3.4.0.CR1


import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * Home object for domain model class Cardcategory.
 * @see .Cardcategory
 * @author Hibernate Tools
 */
@Stateless
public class CardcategoryHome {

    private static final Log log = LogFactory.getLog(CardcategoryHome.class);

    @PersistenceContext private EntityManager entityManager;
    
    public void persist(Cardcategory transientInstance) {
        log.debug("persisting Cardcategory instance");
        try {
            entityManager.persist(transientInstance);
            log.debug("persist successful");
        }
        catch (RuntimeException re) {
            log.error("persist failed", re);
            throw re;
        }
    }
    
    public void remove(Cardcategory persistentInstance) {
        log.debug("removing Cardcategory instance");
        try {
            entityManager.remove(persistentInstance);
            log.debug("remove successful");
        }
        catch (RuntimeException re) {
            log.error("remove failed", re);
            throw re;
        }
    }
    
    public Cardcategory merge(Cardcategory detachedInstance) {
        log.debug("merging Cardcategory instance");
        try {
            Cardcategory result = entityManager.merge(detachedInstance);
            log.debug("merge successful");
            return result;
        }
        catch (RuntimeException re) {
            log.error("merge failed", re);
            throw re;
        }
    }
    
    public Cardcategory findById( CardcategoryId id) {
        log.debug("getting Cardcategory instance with id: " + id);
        try {
            Cardcategory instance = entityManager.find(Cardcategory.class, id);
            log.debug("get successful");
            return instance;
        }
        catch (RuntimeException re) {
            log.error("get failed", re);
            throw re;
        }
    }
}

